### ISSUE TITLE
Other dataset preprocessing?

### ISSUE THREAD

**Issue by bhosalems** [cwmok/Conditional_LapIRN#10]
I checked the learn2reg paper, and they mention you also worked on the abdominal MR-CT dataset. i was wondering what data preprocessing you did as I cant find the code for that dataset.

**Comment by cwmok** [comment]
Hi @bhosalems 

I didn't release the code for the  abdominal MR-CT dataset. For the details of the method used in the abdominal MR-CT dataset. You may refer to slide 15 in [Learn2Reg2021_Tony_oral.pdf](https://github.com/cwmok/Conditional_LapIRN/files/10081436/Learn2Reg2021_Tony_oral.pdf).
