### ISSUE TITLE
Python and PyTorch versions

### ISSUE THREAD

**Issue by annareithmeir** [cwmok/Conditional_LapIRN#12]
Have you tested the code with Python=3.10 and torch=2.0.1 by any chance? 
If not, what are the latest versions the code has been tested - still Python=3.5.2 and torch=1.7.1?

**Comment by cwmok** [comment]
I have tested this codebase with the latest version python and pytorch. If you found that the loss cannot decrease, you may switch the pytorch with different cuda version. In my case, pytorch with cu118 is problematic, but pytorch with cu117 works flawlessly.

**Comment by annareithmeir** [comment]
Thanks, I got it to work with python 3.10, torch 2.0.1 and cu117
