### ISSUE TITLE
MIND-SSC implementation for lung/abdominal MR-CT

### ISSUE THREAD

**Issue by annareithmeir** [cwmok/Conditional_LapIRN#13]
Which MIND-SSC features implementation are you using for the lung/abdominal MR-CT dataset? 

And in your slides of the miccai 2021 oral are you training this dataset unsupervised or semi-supervised? If the latter, do you remember if the unsupervised version gives good results too?

Thanks!

**Comment by cwmok** [comment]
Hi @annareithmeir,

I use the MIND-SSC implementation at https://github.com/multimodallearning/convexAdam/blob/main/convex_adam_utils.py

For the Learn2Reg 2021 challenge, I use semi-supervised loss (with dice loss). I didn't try the unsupervised version for the MR-CT task. However, I did try the unsupervised version for abdominal CT-CT registration. It shows ~10% drop in Dice. The result is in  https://arxiv.org/abs/2306.16997.
