### ISSUE TITLE
How can I use your code to complete the registration if I only have two images of type .png?

### ISSUE THREAD

**Issue by dzz416** [cwmok/Conditional_LapIRN#3]
I dont have the .nii images

**Comment by cwmok** [comment]
Hi @dzz416,

Unfortunately, the answer is no. Our method is a deep learning-based approach, which implies that it requires training with a large-scale dataset before you apply it to any tasks. If you have two images and want to register it, I suggest you try some conventional registration methods, e.g., [Elastix](https://simpleelastix.github.io/), [ANTs ](http://stnava.github.io/ANTs/)and [NiftyReg](http://cmictig.cs.ucl.ac.uk/wiki/index.php/NiftyReg). These methods rely on iterative optimization methods and should work well with your images of type .png.
