### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by TVayne** [cwmok/Conditional_LapIRN#4]
Hi @cwmok. 
In your three works, the oasis dataset is 425 groups of images, but I found that the data on the official website and https://github.com/adalca/medical-datasets/blob/master/neurite-oasis.md are 414 groups. Where can I download these 425 sets of data?
looking forward to your reply

**Comment by cwmok** [comment]
Hi @tzp123456 ,

I downloaded the OASIS-1 dataset in here: https://www.oasis-brains.org/.
