### ISSUE TITLE
About the conditional instance normalization skip connection code

### ISSUE THREAD

**Issue by Zhenyu-040314** [cwmok/Conditional_LapIRN#5]
Hi @cwmok.
        Thank you so much for your work! 
        In your code(line 410 in miccai2021_model.py) ，the equation of the conditional instance normalization is "out = (1. + gamma) * out + beta"，but in your paper, the equation of the conditional instance normalization "out =  gamma * out + beta". And in fig.1(b) of your paper, the equation of the conditional instance normalization  is also "out=  gamma * Instance Norm(self.norm(input)) + beta"
I am confusing about that. Looking forward to your reply！
![QQ截图20220310094646](https://user-images.githubusercontent.com/74998993/157574098-e99f7195-9f45-41d9-a1b9-f85fbd299044.jpg)
![QQ截图20220310094923](https://user-images.githubusercontent.com/74998993/157574112-d6afee03-a74b-44b9-be5a-90e06e11acc6.jpg)
![QQ截图20220310100147](https://user-images.githubusercontent.com/74998993/157574137-2003f287-ec50-4f39-9338-63f560199672.jpg)

**Comment by cwmok** [comment]
Hi @zhenyu202020 ,

You can think of the (1+gamma) in the code is equivalent to the gamma in the paper/figure. The "1" here is to preserve the identity of features. During training, gamma and beta are learnable weights and will be initialized to a numer that close to zero. The "1" preserves the identity of features and hence stabilizes the training.

**Comment by Zhenyu-040314** [comment]
Thanks for the fast response!
I have solved my confusion. 
Thank you very much!

**Comment by Zhenyu-040314** [comment]
Hi @cwmok.
Sorry to bother you again.
![image](https://user-images.githubusercontent.com/74998993/158060656-7edff6ae-9ce9-4215-adcb-dc1a13a14dd0.png)
I don't quite understand why  "F_X_Y * norm_vector" and what does “norm_vector” stand for?
Looking forward to your reply！

**Comment by cwmok** [comment]
Hi @zhenyu202020,

You may notice, unlike VoxelMorph, our methods output a normalized deformation field, i.e., within [-1, 1]. The `F_X_Y` refers to the displacement vector field (F) that aligns image "X" to "Y" space. `norm_vector` transforms the normalized displacement vector field to an unnormalized one, similar to the output of VoxelMorph. Note that, the correct multiplier that transforms a normalized deformation field to an unnormalized one should be equal to (image_dim - 1)/2. But, during the experiments in our paper, all the results use (image_dim-1). Therefore, we keep it as (image_dim-1).  You should keep that in mind when you want to visualize the deformation field/obtain an unnormalized deformation field.

**Comment by Zhenyu-040314** [comment]
Thank you for your patience in replying！
