### ISSUE TITLE
Gradient explosion

### ISSUE THREAD

**Issue by tracob-github** [cwmok/Conditional_LapIRN#8]
Hi, there seems to be a gradient explosion during training stage1. May I ask why this problem occurs?
![1666533816498](https://user-images.githubusercontent.com/59277274/197396624-b161d8e1-5eca-4b32-964e-8d69dfe8ef9f.png)

**Comment by cwmok** [comment]
Hi @tracob-github,

How do you define "gradient explosion"? The image looks fine in low-resolution space.

**Comment by tracob-github** [comment]
Thank you for your reply. I finally found out what the problem was.
