### ISSUE TITLE
The Model folder doesn't exist!

### ISSUE THREAD

**Issue by mogvision** [cwmok/Conditional_LapIRN#9]
Hi, thanks for sharing your nice work. I cannot find the pre-trained model, i.e. "Model/LDR_OASIS_NCC_unit_disp_add_fea4_reg01_10_lite_stagelvl3_54000.pth"
Would you please upload it? 
Thanks and bests

**Comment by cwmok** [comment]
Hi @mogvision,

I have uploaded the pre-trained file to "Model" folder for the "lite" version.
For 2D and crop versions, I will update it next week.

Thanks for your interest in our work.

**Comment by mogvision** [comment]
> Hi @mogvision,
> 
> I have uploaded the pre-trained file to "Model" folder for the "lite" version. For 2D and crop versions, I will update it next week.
> 
> Thanks for your interest in our work.

Thanks for sharing the file. Best wishes to you and your team, Mori
